[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[programs.mainnet]
nft_candy_machine = "cndypf6mGC57KHkPF6LXrf7esXgXXAUjuBr8wnK7d6V"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 test/*.ts"

[workspace]
members = ["nft-candy-machine"]
